-- lua/lvim/icons.lua
return {
	git = {
		LineAdded = "",
		LineModified = "",
		LineRemoved = "",
		LineIgnored = "",

		FileDeleted = "",
		FileIgnored = "",
		FileRenamed = "",
		FileAdded = "",
		FileUnmerged = "",
		FileUnstaged = "",
		FileStaged = "",
		FileUntracked = "",
		FileConflict = "",
		Diff = "",
		Repo = "",
		Branch = "",
	},
	diagnostics = {
		BoldError = "",
		Error = "",
		BoldWarning = "",
		Warning = "",
		BoldInformation = "",
		Information = "",
		BoldQuestion = "",
		Question = "",
		BoldHint = "",
		Hint = "",
		Debug = "",
		Trace = "",
	},
	dap = {
		Breakpoint = "",
		BreakpointCondition = "",
		Stopped = "",
	},
}
