gui:
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never -s --commit-style=omit --hunk-header-decoration-style=omit
    # externalDiffCommand: difft --color=always --display=side-by-side --tab-width=2


keybinding:
  universal:
    scrollUpMain: '<c-k>'
    scrollDownMain: '<c-j>'
