return {}
--
-- -- Overriding built in features so disable them
-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
--
-- return {
-- 	{
-- 		"nvim-tree/nvim-tree.lua",
-- 		config = function()
-- 			local api = require("nvim-tree.api")
--
-- 			require("nvim-tree").setup({
-- 				disable_netrw = true,
-- 				-- hijack_directories = {
-- 				-- 	enable = true,
-- 				-- },
-- 				update_cwd = true,
-- 				update_focused_file = {
-- 					enable = true,
-- 					update_root = true,
-- 				},
-- 				-- filesystem_watchers = {
-- 				-- 	enable = true,
-- 				-- },
-- 				-- sync_root_with_cwd = true,
-- 				-- respect_buf_cwd = true,
-- 				-- view = {
-- 				-- 	float = {
-- 				-- 		enable = false,
-- 				-- 		open_win_config = {
-- 				-- 			width = 60,
-- 				-- 			row = 2,
-- 				-- 			col = 11,
-- 				-- 		},
-- 				-- 	},
-- 				-- },
-- 				-- renderer = {
-- 				-- 	add_trailing = true,
-- 				-- 	highlight_git = true,
-- 				-- },
-- 				actions = {
-- 					-- change_dir = {
-- 					-- 	enable = true,
-- 					-- },
-- 					open_file = {
-- 						quit_on_open = true,
-- 					},
-- 				},
-- 			})
--
-- 			vim.keymap.set("n", "<leader>e", api.tree.toggle)
-- 			vim.keymap.set("n", "-", function()
-- 				api.tree.find_file({ open = true, update_root = true, focus = true })
-- 			end)
-- 		end,
-- 	},
-- 	{ "adelarsq/image_preview.nvim", opts = {} },
-- }
