#!/bin/bash

options=(
	  style=round
    active_color=0x4feb4372 
     # active_color=0x00FF00FF
    inactive_color=0x00000000 
    width=2.0 
    hidpi=on 
    order=above
    )

borders "${options[@]}"
